#############################################################################
# Makefile for building: GateWay
# Generated by qmake (2.01a) (Qt 4.5.0) on: ?? 6? 11 08:53:40 2017
# Project:  GateWay.pro
# Template: app
# Command: /opt/qt-embedded-linux-opensource-src-4.5.0/bin/qmake-arm -unix -o Makefile GateWay.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -D_TTY_POSIX_ -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/include/QtCore -I/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/include/QtNetwork -I/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/include/QtGui -I/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/include/QtSql -I/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/include -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.5.0-arm-linux/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib -lQtSql -L/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib -lQtGui -lQtNetwork -lQtCore -lm -lrt -ldl -lpthread
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-embedded-linux-opensource-src-4.5.0/bin/qmake-arm
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		port/posix_qextserialport.cpp \
		port/qextserialbase.cpp \
		port/qextserialport.cpp \
		service/serialclass.cpp \
		service/socketclass.cpp \
		maincode/nodeset/airirda.cpp \
		maincode/nodeset/curtain.cpp \
		maincode/nodeset/moudle.cpp \
		maincode/nodeset/pir.cpp \
		maincode/nodeset/relay.cpp \
		maincode/nodeset/relay2.cpp \
		maincode/nodeset/rfidlock.cpp \
		maincode/nodeset/smoke.cpp \
		maincode/nodeset/temperature.cpp \
		maincode/nodeset/touch.cpp \
		maincode/moudleset.cpp moc_widget.cpp \
		moc_qextserialbase.cpp \
		moc_qextserialport.cpp \
		moc_serialclass.cpp \
		moc_socketclass.cpp \
		moc_airirda.cpp \
		moc_curtain.cpp \
		moc_pir.cpp \
		moc_relay.cpp \
		moc_relay2.cpp \
		moc_rfidlock.cpp \
		moc_smoke.cpp \
		moc_temperature.cpp \
		moc_touch.cpp \
		moc_moudleset.cpp
OBJECTS       = main.o \
		widget.o \
		posix_qextserialport.o \
		qextserialbase.o \
		qextserialport.o \
		serialclass.o \
		socketclass.o \
		airirda.o \
		curtain.o \
		moudle.o \
		pir.o \
		relay.o \
		relay2.o \
		rfidlock.o \
		smoke.o \
		temperature.o \
		touch.o \
		moudleset.o \
		moc_widget.o \
		moc_qextserialbase.o \
		moc_qextserialport.o \
		moc_serialclass.o \
		moc_socketclass.o \
		moc_airirda.o \
		moc_curtain.o \
		moc_pir.o \
		moc_relay.o \
		moc_relay2.o \
		moc_rfidlock.o \
		moc_smoke.o \
		moc_temperature.o \
		moc_touch.o \
		moc_moudleset.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/lex.prf \
		GateWay.pro
QMAKE_TARGET  = GateWay
DESTDIR       = 
TARGET        = GateWay

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GateWay.pro  /usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib/libQtSql.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib/libQtCore.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib/libQtGui.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile GateWay.pro
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/g++.conf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/release.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib/libQtSql.prl:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib/libQtCore.prl:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib/libQtGui.prl:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile GateWay.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GateWay1.0.0 || $(MKDIR) .tmp/GateWay1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GateWay1.0.0/ && $(COPY_FILE) --parents widget.h port/posix_qextserialport.h port/qextserialbase.h port/qextserialport.h service/serialclass.h service/socketclass.h maincode/nodeset/airirda.h maincode/nodeset/curtain.h maincode/nodeset/moudle.h maincode/nodeset/pir.h maincode/nodeset/relay.h maincode/nodeset/relay2.h maincode/nodeset/rfidlock.h maincode/nodeset/smoke.h maincode/nodeset/temperature.h maincode/nodeset/touch.h maincode/moudleset.h .tmp/GateWay1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp port/posix_qextserialport.cpp port/qextserialbase.cpp port/qextserialport.cpp service/serialclass.cpp service/socketclass.cpp maincode/nodeset/airirda.cpp maincode/nodeset/curtain.cpp maincode/nodeset/moudle.cpp maincode/nodeset/pir.cpp maincode/nodeset/relay.cpp maincode/nodeset/relay2.cpp maincode/nodeset/rfidlock.cpp maincode/nodeset/smoke.cpp maincode/nodeset/temperature.cpp maincode/nodeset/touch.cpp maincode/moudleset.cpp .tmp/GateWay1.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/GateWay1.0.0/ && (cd `dirname .tmp/GateWay1.0.0` && $(TAR) GateWay1.0.0.tar GateWay1.0.0 && $(COMPRESS) GateWay1.0.0.tar) && $(MOVE) `dirname .tmp/GateWay1.0.0`/GateWay1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GateWay1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_qextserialbase.cpp moc_qextserialport.cpp moc_serialclass.cpp moc_socketclass.cpp moc_airirda.cpp moc_curtain.cpp moc_pir.cpp moc_relay.cpp moc_relay2.cpp moc_rfidlock.cpp moc_smoke.cpp moc_temperature.cpp moc_touch.cpp moc_moudleset.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_qextserialbase.cpp moc_qextserialport.cpp moc_serialclass.cpp moc_socketclass.cpp moc_airirda.cpp moc_curtain.cpp moc_pir.cpp moc_relay.cpp moc_relay2.cpp moc_rfidlock.cpp moc_smoke.cpp moc_temperature.cpp moc_touch.cpp moc_moudleset.cpp
moc_widget.cpp: maincode/moudleset.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/moudle.h \
		maincode/nodeset/temperature.h \
		maincode/nodeset/smoke.h \
		maincode/nodeset/pir.h \
		maincode/nodeset/touch.h \
		maincode/nodeset/relay.h \
		maincode/nodeset/airirda.h \
		maincode/nodeset/curtain.h \
		maincode/nodeset/rfidlock.h \
		maincode/nodeset/relay2.h \
		widget.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_qextserialbase.cpp: port/qextserialbase.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) port/qextserialbase.h -o moc_qextserialbase.cpp

moc_qextserialport.cpp: port/posix_qextserialport.h \
		port/qextserialbase.h \
		port/qextserialport.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) port/qextserialport.h -o moc_qextserialport.cpp

moc_serialclass.cpp: port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/serialclass.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) service/serialclass.h -o moc_serialclass.cpp

moc_socketclass.cpp: service/socketclass.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) service/socketclass.h -o moc_socketclass.cpp

moc_airirda.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/airirda.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/airirda.h -o moc_airirda.cpp

moc_curtain.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/curtain.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/curtain.h -o moc_curtain.cpp

moc_pir.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/pir.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/pir.h -o moc_pir.cpp

moc_relay.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/relay.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/relay.h -o moc_relay.cpp

moc_relay2.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/relay2.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/relay2.h -o moc_relay2.cpp

moc_rfidlock.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/rfidlock.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/rfidlock.h -o moc_rfidlock.cpp

moc_smoke.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/smoke.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/smoke.h -o moc_smoke.cpp

moc_temperature.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/temperature.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/temperature.h -o moc_temperature.cpp

moc_touch.cpp: maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/touch.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/nodeset/touch.h -o moc_touch.cpp

moc_moudleset.cpp: service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/moudle.h \
		maincode/nodeset/temperature.h \
		maincode/nodeset/smoke.h \
		maincode/nodeset/pir.h \
		maincode/nodeset/touch.h \
		maincode/nodeset/relay.h \
		maincode/nodeset/airirda.h \
		maincode/nodeset/curtain.h \
		maincode/nodeset/rfidlock.h \
		maincode/nodeset/relay2.h \
		maincode/moudleset.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/moc $(DEFINES) $(INCPATH) maincode/moudleset.h -o moc_moudleset.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm-embedded/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		maincode/moudleset.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/moudle.h \
		maincode/nodeset/temperature.h \
		maincode/nodeset/smoke.h \
		maincode/nodeset/pir.h \
		maincode/nodeset/touch.h \
		maincode/nodeset/relay.h \
		maincode/nodeset/airirda.h \
		maincode/nodeset/curtain.h \
		maincode/nodeset/rfidlock.h \
		maincode/nodeset/relay2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		maincode/moudleset.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/moudle.h \
		maincode/nodeset/temperature.h \
		maincode/nodeset/smoke.h \
		maincode/nodeset/pir.h \
		maincode/nodeset/touch.h \
		maincode/nodeset/relay.h \
		maincode/nodeset/airirda.h \
		maincode/nodeset/curtain.h \
		maincode/nodeset/rfidlock.h \
		maincode/nodeset/relay2.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

posix_qextserialport.o: port/posix_qextserialport.cpp port/posix_qextserialport.h \
		port/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o port/posix_qextserialport.cpp

qextserialbase.o: port/qextserialbase.cpp port/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialbase.o port/qextserialbase.cpp

qextserialport.o: port/qextserialport.cpp port/qextserialport.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o port/qextserialport.cpp

serialclass.o: service/serialclass.cpp service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialclass.o service/serialclass.cpp

socketclass.o: service/socketclass.cpp service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socketclass.o service/socketclass.cpp

airirda.o: maincode/nodeset/airirda.cpp maincode/nodeset/airirda.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o airirda.o maincode/nodeset/airirda.cpp

curtain.o: maincode/nodeset/curtain.cpp maincode/nodeset/curtain.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curtain.o maincode/nodeset/curtain.cpp

moudle.o: maincode/nodeset/moudle.cpp maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moudle.o maincode/nodeset/moudle.cpp

pir.o: maincode/nodeset/pir.cpp maincode/nodeset/pir.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pir.o maincode/nodeset/pir.cpp

relay.o: maincode/nodeset/relay.cpp maincode/nodeset/relay.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o relay.o maincode/nodeset/relay.cpp

relay2.o: maincode/nodeset/relay2.cpp maincode/nodeset/relay2.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o relay2.o maincode/nodeset/relay2.cpp

rfidlock.o: maincode/nodeset/rfidlock.cpp maincode/nodeset/rfidlock.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rfidlock.o maincode/nodeset/rfidlock.cpp

smoke.o: maincode/nodeset/smoke.cpp maincode/nodeset/smoke.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smoke.o maincode/nodeset/smoke.cpp

temperature.o: maincode/nodeset/temperature.cpp maincode/nodeset/temperature.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temperature.o maincode/nodeset/temperature.cpp

touch.o: maincode/nodeset/touch.cpp maincode/nodeset/touch.h \
		maincode/nodeset/moudle.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o touch.o maincode/nodeset/touch.cpp

moudleset.o: maincode/moudleset.cpp maincode/moudleset.h \
		service/serialclass.h \
		port/posix_qextserialport.h \
		port/qextserialbase.h \
		service/socketclass.h \
		maincode/nodeset/moudle.h \
		maincode/nodeset/temperature.h \
		maincode/nodeset/smoke.h \
		maincode/nodeset/pir.h \
		maincode/nodeset/touch.h \
		maincode/nodeset/relay.h \
		maincode/nodeset/airirda.h \
		maincode/nodeset/curtain.h \
		maincode/nodeset/rfidlock.h \
		maincode/nodeset/relay2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moudleset.o maincode/moudleset.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_qextserialbase.o: moc_qextserialbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialbase.o moc_qextserialbase.cpp

moc_qextserialport.o: moc_qextserialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialport.o moc_qextserialport.cpp

moc_serialclass.o: moc_serialclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialclass.o moc_serialclass.cpp

moc_socketclass.o: moc_socketclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_socketclass.o moc_socketclass.cpp

moc_airirda.o: moc_airirda.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_airirda.o moc_airirda.cpp

moc_curtain.o: moc_curtain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_curtain.o moc_curtain.cpp

moc_pir.o: moc_pir.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pir.o moc_pir.cpp

moc_relay.o: moc_relay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_relay.o moc_relay.cpp

moc_relay2.o: moc_relay2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_relay2.o moc_relay2.cpp

moc_rfidlock.o: moc_rfidlock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rfidlock.o moc_rfidlock.cpp

moc_smoke.o: moc_smoke.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_smoke.o moc_smoke.cpp

moc_temperature.o: moc_temperature.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_temperature.o moc_temperature.cpp

moc_touch.o: moc_touch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_touch.o moc_touch.cpp

moc_moudleset.o: moc_moudleset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moudleset.o moc_moudleset.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

